"""Initial UWS schema

Revision ID: 5ab72a20365b
Revises:
Create Date: 2024-09-12 19:02:23.855138+00:00

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5ab72a20365b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
